---
title: "Gov 50 Final Project"
author: "Marc P."
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project Proposal

Proposal: Analyzing Monthly Temporal Patterns of Terrorism in Western Europe (1965-2005)

Data Source:
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/HJHGYA

Research Question: How is the frequency of terrorist killings in Western European countries related to different months of the year during the period 1965-2005?

Hypothesis: Drawing from the seasonality effect observed in various socio-political phenomena, it is hypothesized that certain months might experience higher frequencies of terrorist killings compared to others. This could be due to various reasons such as favorable climatic conditions for operations, significant political or social events in specific months, or even strategic timing choices made by terrorist organizations. For instance, months with significant public events or holidays might be targeted more frequently due to the visibility and impact of such attacks.


Explanatory Variable(s) of Interest:

Month of the Year: This will be a categorical variable indicating each of the twelve months. Each terrorist killing will be tagged to a specific month based on the date of occurrence.

Outcome Variable of Interest:

Frequency of Terrorist Killings: This variable represents the number of terrorist killings in a given month in Western European countries. It will be measured as count data based on the provided dataset's information.


Expected Patterns:

Supportive Pattern: An observed consistent increase in the frequency of terrorist killings in specific months across the years would support our hypothesis. For instance, if July repeatedly has higher incidences due to national holidays or events, it would validate our assumption about strategic timing.

Contradictory Pattern: If the data shows no discernible pattern or if terrorist activities are evenly distributed across months, it would challenge our hypothesis and suggest that month-based seasonality might not play a crucial role in the timing of terrorist activities during the given period.
